name: Ngml CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ngml-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, intl, bcmath
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            .github/workflows/ci.yml  # Cache busting

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Force Clean NPM Install
        run: |
          npm ci --no-cache
          # Alternative nuclear option:
          # rm -rf node_modules && npm ci

      # Rest of your steps remain the same
